"""add extra_data and model_version to predictions

Revision ID: 868e464ec1c2
Revises: 6b94c7970a64
Create Date: 2026-08-30 05:22:09.641450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868e464ec1c2'
down_revision: Union[str, Sequence[str], None] = '6b94c7970a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('predictions', sa.Column('model_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_predictions_disease_type'), 'predictions', ['disease_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_disease_type'), table_name='predictions')
    op.drop_column('predictions', 'model_version')
    op.drop_column('predictions', 'extra_data')
    # ### end Alembic commands ###
